# Generated by Django 5.0.7 on 2024-09-13 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('documents', '0003_remove_document_id_remove_document_id_vdb_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_assistant',
            name='company_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='chat_assistant_documents',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistant_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat_assistant_documents',
            name='id_chat_assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistant_documents', to='chat.chat_assistant'),
        ),
        migrations.AlterField(
            model_name='chat_assistant_documents',
            name='id_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistant_documents', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='chat_history',
            name='id_chat_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_historys', to='chat.chat_session'),
        ),
        migrations.AlterField(
            model_name='chat_history',
            name='useful',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='chat_session',
            name='id_end_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_sessions', to='chat.chat_session_end_reason'),
        ),
    ]
