# Generated by Django 5.0.7 on 2024-09-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_assistant_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_assistant',
            name='llm_model',
            field=models.CharField(default='gpt-4o-mini', max_length=50),
        ),
    ]
