# Generated by Django 5.0.7 on 2024-08-31 20:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_category',
            fields=[
                ('id_document_category', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'document_category',
            },
        ),
        migrations.CreateModel(
            name='Document_department',
            fields=[
                ('id_document_department', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'document_department',
            },
        ),
        migrations.CreateModel(
            name='Document_type',
            fields=[
                ('id_document_type', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'document_type',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=200)),
                ('resume', models.CharField(default='', max_length=800)),
                ('document_path', models.CharField(default='', max_length=1024)),
                ('s3_document_path', models.CharField(default='', max_length=1024)),
                ('id_vdb', models.CharField(default='', max_length=50)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(default='', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('id_document_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.document_category')),
                ('id_document_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.document_department')),
                ('id_document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.document_type')),
            ],
            options={
                'db_table': 'document',
            },
        ),
    ]
