# Generated by Django 5.0.7 on 2024-08-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='s3_document_path',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
