# Generated by Django 5.0.7 on 2024-09-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_document_id_remove_document_id_vdb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='resume',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
