# Generated by Django 5.0.7 on 2024-09-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id_document',
            field=models.UUIDField(default='<function uuid4 at 0x7f024de62440>', primary_key=True, serialize=False),
        ),
    ]
