# Generated by Django 5.0.7 on 2024-09-15 00:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_document_id_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id_document',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True),
        ),
    ]
